### ISSUE TITLE
Sync fails when multiple folders are open in Workspace

### ISSUE THREAD

**Issue by riazmaulvi** [CatStarwind/FileSync#6]
File Sync will only sync the first folder when multiple folders in the same workspace are open. For example:

Open folder A, B, C, D in a workspace (each folder has its own subfolders.) Make a change to any  file in any subfolder in "A" syncs as expected. Any changes to B, C, or D are not synced. 

File Sync config for above folders:
```javascript
"filesync.mappings": [
        {
            "source": "D:\\My-Projects\\A",
            "destination": "E:\\html\\A"
        },
        {
            "source": "D:\\My-Projects\\B",
            "destination": "E:\\B"
        },
        {
            "source": "D:\\My-Projects\\C",
            "destination": "E:\\html\\C"
        },
        {
            "source": "D:\\My-Projects\\D",
            "destination": "E:\\html\\D"
        }
    ],

Best Regards,
Riaz

**Comment by riazmaulvi** [comment]
I have fixed the above issue; I am attaching the updated fileSync.ts to this comment.

Here is the code that was updated: Lines 57 - 87

```typescript
//Check if workspace/folder.
if (vscode.workspace.workspaceFolders) {
	var folders = vscode.workspace.workspaceFolders;

	// iterate through the folders in the workspace
	folders.forEach((folder) => {
		let root = folder ? folder.uri.fsPath : "";

		if (root !== "") {
			this.log(`root: ${root.toLowerCase()}.`);
			//Look for mapping.
			let map = this.mappings().find(m => m.source.toLowerCase() === root.toLowerCase());

			if(map){
				//Mapping found, enable FileSync for map.
				this.onSave = vscode.workspace.onDidSaveTextDocument((file) => { if(map){ this.syncSave(map, file); } });
				this.context.subscriptions.push(this.onSave);
				this.enabled = true;
				this.sbar.show();
				vscode.window.showInformationMessage("File Sync is Active.");
				this.log(`Save listener enabled for ${map.source}.`);
			} else {
				if(!auto) { vscode.window.showErrorMessage("No mapping available!"); }
				this.log(`Failed! ${root} not mapped.`);
			}

		} else {
			this.log("Aborting, not in a workspace.");
		}
	});
}
```





Best Regards,
Riaz
[fileSync.ts.txt](https://github.com/CatStarwind/FileSync/files/4571406/fileSync.ts.txt)

**Comment by riazmaulvi** [comment]
Reopening this issue as I accidentally closed it. Let me know if there is anything I can do to assist.

Thanks,
Riaz.

**Comment by GilliamOperator** [comment]
Awesome! The extension was originally meant for single folder Workspaces. I integrated your changes and decided to fully support having multiple folders in a workspace. You can check commit https://github.com/CatStarwind/FileSync/commit/f05fea6c1826a4d6f0fd09206c71e99ca74cf3e6.
